on:
  push:
    branches:
      - '**'
    paths-ignore:
      - .github/**
      - .idea/**
  workflow_dispatch:
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Run Tests
        run: ./gradlew test --no-daemon
